name: hybrid_drift_detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip
  - numpy=1.23.5
  - pandas=2.3.1
  - scipy=1.15.3
  - scikit-learn=1.7.1
  - matplotlib-base=3.10.5
  - joblib=1.5.1
  - tqdm=4.67.1
  - seaborn=0.13.0
  - numba=0.57.1
  - statsmodels=0.14.5
  - scikit-image=0.22.0
  - pillow=10.4.0
  - lightgbm=4.5.0
  - pytz
  - python-dateutil
  - pip:
      # Quantum
      - pennylane==0.38.1
      - pennylane-lightning==0.38.0
      - alibi-detect==0.11.5
      - cloudpickle==3.1.1
      - scipy==1.15.3
      - scikit-learn==1.7.1
      - numpy==1.23.5
      - pandas==2.3.1
      - matplotlib==3.10.5
      - tqdm==4.67.1
      - joblib==1.5.1
      - jupyterlab==4.4.5
      - ipykernel==6.30.1
      - ipywidgets==8.1.8
      - notebook==7.4.5
      

      
